version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/teste
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/composer_and_permission
      timeout: 300
      runas: root
