#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run check-format

npm run check-lint

npm run check-types ||
(
    echo '❌ Failed Type check. ❌
            Try to make the changes required above.'
    false;
)

echo '🤖 ... Alright... Code looks good to me... Trying to build now. 🤖'

npm run build ||
(
    echo '❌👷🔨❌ Ops! Your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
